using System.Linq;
using Content.Client.RichText;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.MassMedia.Ui;

[GenerateTypedNameReferences]
public sealed partial class NewsArticleCard : Button
{
    // Thresholds are arbitrarily chosen based on what looks decent at default size
    private const int ShortLabelThreshold = 25;
    private const int LongLabelThreshold = 65;
    private bool _expanded;
    private readonly Type[] _allowedRichTextTags;

    public Action? OnDeletePressed;
    public int ArticleNumber;

    private static string ShortenString(string? text, int threshold)
    {
        if (text is null)
        {
            return "";
        }

        return text.Length <= threshold ? text : $"{text[..threshold].TrimEnd()}...";
    }

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = ShortenString(value, ShortLabelThreshold);
    }

    public string? Content
    {
        get;
        set
        {
            field = value;
            SetContentLabel();
        }
    }

    public string? Author
    {
        get;
        set
        {
            field = value;
            AuthorLabel.Text = field ?? "";
        }
    }

    public TimeSpan? PublicationTime
    {
        get;
        set
        {
            field = value;
            PublishTimeLabel.Text = value?.ToString(@"hh\:mm\:ss") ?? "";
        }
    }

    public NewsArticleCard()
    {
        RobustXamlLoader.Load(this);
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke();
        OnPressed += OnContentPressed;

        // Heading tags look weird in the news console UI, so do not allow them
        var allowedTagsSet = UserFormattableTags.BaseAllowedTags.ToHashSet();
        allowedTagsSet.Remove(typeof(HeadingTag));
        _allowedRichTextTags = allowedTagsSet.ToArray();
    }

    private void OnContentPressed(ButtonEventArgs obj)
    {
        _expanded = !_expanded;
        SetContentLabel();
    }

    private void SetContentLabel()
    {
        var msg = FormattedMessage.FromMarkupPermissive(Content ?? "");
        if (!_expanded)
        {
            // Don't count rich text tags in the length when shortening
            // This does mean rich text won't render unless expanded
            msg = FormattedMessage.FromMarkupPermissive(ShortenString(msg.ToString(), LongLabelThreshold));
            msg.TrimEnd();
        }

        ContentLabel.SetMessage(msg, _allowedRichTextTags);
    }
}
