using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.MassMedia.Ui;

[GenerateTypedNameReferences]
public sealed partial class NewsArticleCard : Button
{
    private const int ShortLabelThreshold = 30;
    private bool _expanded;

    public Action? OnDeletePressed;
    public int ArtcileNumber;

    private static string ShortenString(string? text, int threshold)
    {
        if (text is null)
        {
            return "";
        }
        return text.Length <= threshold ? text : $"{text[..threshold]}...";
    }

    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = ShortenString(value, ShortLabelThreshold);
    }

    public string? Content
    {
        get;
        set
        {
            field = value;
            SetContentLabel();
        }
    }

    public string? Author
    {
        get;
        set
        {
            field = value;
            AuthorLabel.Text = field ?? "";
        }
    }

    public TimeSpan? PublicationTime
    {
        get;
        set
        {
            field = value;
            PublishTimeLabel.Text = value?.ToString(@"hh\:mm\:ss") ?? "";
        }
    }

    public NewsArticleCard()
    {
        RobustXamlLoader.Load(this);
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke();
        OnPressed += OnContentPressed;
    }

    private void OnContentPressed(ButtonEventArgs obj)
    {
        Log.Debug(_expanded.ToString());
        _expanded = !_expanded;
        Log.Debug(_expanded.ToString());
        SetContentLabel();
    }

    private void SetContentLabel()
    {
        if (_expanded)
        {
            ContentLabel.SetMessage(Content ?? "");
        }
        else
        {
            ContentLabel.SetMessage(ShortenString(Content, ShortLabelThreshold));
        }

        if (Content is not null)
            Log.Debug(Content);
    }
}
